# docker-compose up -d --build 
version: "3"
services:
  node-app:
    restart: always
    build: .
    ports:
      - 8082:8081
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: